### ISSUE TITLE
Frontend task 1 (plan way to bridge program to user)

### ISSUE THREAD

**Issue by Jyustin** [jesa06/groupflask#4]
create plan for how you intend to integrate our tetris python program into our group flask so It can be playable in a browser. I'd suggest creating a tab on our group flask that we could use to bridge the user to our program.

**Comment by jesa06** [comment]
1. I already made a separate screen with a tab in the navbar called "Play Game!". Once we have some backend code, I can produce frontend code to connect it and have an output, with the backend code. 
2.  will start to create a record and list the output as a table. The table will hold records/data about players sorted by their high score, but also including their names.
