### ISSUE TITLE
Dev Ops task 1 (work with frontend and backend)

### ISSUE THREAD

**Issue by Jyustin** [jesa06/groupflask#5]
work with frontend and backend to see how both programs will work with each other. Since frontend and backend will be coded in different languages we need to make sure they can come together and give the user the ability to use our program. Also work with Backend to test for bugs.

**Comment by shruthim0** [comment]
Work with the Frontend developer to develop a scoreboard. Update website through AWS Deployment Process. Customize our blog, and add logo and background. Work with Frontend developer to decide what API to implement into project. Decided to implement Inpirational Quote API.
