### ISSUE TITLE
frontend task 2 (bridge game and user)

### ISSUE THREAD

**Issue by Jyustin** [jesa06/groupflask#7]
work on building a barebones frontend to our game that can at minimum have user use button to start game. Anything else would be extra. build a framework for frontend first.

**Comment by jesa06** [comment]
1. When we click on our play game button on the navbar, it will show a screen with "Tetris" and a play button and then it will prompt for the player's name.
2. After you enter the name it will start the game 
3. I will then use JavaScript to build a list and dictionary, keeping records of all of the players. I will then code it to sort by highscore. 
4. On the Game Over screen under the 'F5' to restart, I will also have a view scoreboard button, again of all the players and sorted by highest score to lowest score.
